
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 14 08:54:25 CST 2026
//----------------------------------------------------

package fes.aragon.tablerointerprete.analizador;

import fes.aragon.tablerointerprete.comando.Comando;
import java_cup.runtime.Scanner;
import java_cup.runtime.Symbol;
import java_cup.runtime.SymbolFactory;
import java_cup.runtime.lr_parser;

import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu May 14 08:54:25 CST 2026
  */
public class parser extends lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\014\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\005\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\004\000\002\004\006\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\022\003\012\004\007\005\013\006\011\007" +
    "\005\010\006\011\014\012\016\001\002\000\004\002\026" +
    "\001\002\000\026\002\ufffa\003\ufffa\004\ufffa\005\ufffa\006" +
    "\ufffa\007\ufffa\010\ufffa\011\ufffa\012\ufffa\013\ufffa\001\002" +
    "\000\026\002\ufff9\003\ufff9\004\ufff9\005\ufff9\006\ufff9\007" +
    "\ufff9\010\ufff9\011\ufff9\012\ufff9\013\ufff9\001\002\000\004" +
    "\014\024\001\002\000\026\002\ufffe\003\ufffe\004\ufffe\005" +
    "\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe\013\ufffe" +
    "\001\002\000\026\002\ufffb\003\ufffb\004\ufffb\005\ufffb\006" +
    "\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\013\ufffb\001\002" +
    "\000\026\002\ufff6\003\ufff6\004\ufff6\005\ufff6\006\ufff6\007" +
    "\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\001\002\000\026" +
    "\002\ufffc\003\ufffc\004\ufffc\005\ufffc\006\ufffc\007\ufffc\010" +
    "\ufffc\011\ufffc\012\ufffc\013\ufffc\001\002\000\004\014\023" +
    "\001\002\000\024\002\000\003\012\004\007\005\013\006" +
    "\011\007\005\010\006\011\014\012\016\001\002\000\004" +
    "\014\017\001\002\000\022\003\012\004\007\005\013\006" +
    "\011\007\005\010\006\011\014\012\016\001\002\000\024" +
    "\003\012\004\007\005\013\006\011\007\005\010\006\011" +
    "\014\012\016\013\022\001\002\000\026\002\uffff\003\uffff" +
    "\004\uffff\005\uffff\006\uffff\007\uffff\010\uffff\011\uffff\012" +
    "\uffff\013\uffff\001\002\000\026\002\ufff7\003\ufff7\004\ufff7" +
    "\005\ufff7\006\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7\013" +
    "\ufff7\001\002\000\026\002\ufff8\003\ufff8\004\ufff8\005\ufff8" +
    "\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\013\ufff8\001" +
    "\002\000\004\014\025\001\002\000\026\002\ufffd\003\ufffd" +
    "\004\ufffd\005\ufffd\006\ufffd\007\ufffd\010\ufffd\011\ufffd\012" +
    "\ufffd\013\ufffd\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\010\002\003\003\014\004\007\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\020" +
    "\001\001\000\002\001\001\000\006\003\017\004\007\001" +
    "\001\000\004\004\020\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public Lexer lex;

    // ¡Aquí está nuestra lista para el Camino B!
    public ArrayList<Comando> listaComandos = new ArrayList<>();

    // Constructor opcional para pasar el lexer fácilmente
    public parser(Lexer lex) {
        super(lex);
        this.lex = lex;
    }

    // Método para manejar errores sintácticos
    public void syntax_error(Symbol st) {
        throw new RuntimeException("Error sintáctico: Componente <" + st.value + "> no esperado. Línea " +
        (lex.getYyline() + 1) + ", Columna " + (lex.getYycolumn() + 1));
    }

    // Método para errores irrecuperables
    public void unrecovered_syntax_error(Symbol st) throws Exception {
        System.out.println("Error sintáctico irrecuperable en la línea " +
                           (lex.getYyline() + 1) + ", Columna " + (lex.getYycolumn() + 1));
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= error 
            {
              Object RESULT =null;
		
        RESULT = new ArrayList<>();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= REPITE NUMERO lista_instrucciones PARAR 
            {
              Object RESULT =null;
		int nleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer n = (Integer)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int lileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int liright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object li = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        ArrayList<Comando> l = new ArrayList<>();
        // ¡LA MAGIA DEL COMPILADOR! Multiplicamos el bloque interno 'n' veces
        for(int i = 0; i < n; i++){
            // Agregamos el (ArrayList<Comando>) justo antes de li
            l.addAll((ArrayList<Comando>) li);
        }
        RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= MOVER NUMERO 
            {
              Object RESULT =null;
		int nleft = ((Symbol)CUP$parser$stack.peek()).left;
		int nright = ((Symbol)CUP$parser$stack.peek()).right;
		Integer n = (Integer)((Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<Comando> l = new ArrayList<>(); l.add(new Comando("mover", n)); RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= ARRIBA 
            {
              Object RESULT =null;
		
        ArrayList<Comando> l = new ArrayList<>(); l.add(new Comando("arriba")); RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= ABAJO 
            {
              Object RESULT =null;
		
        ArrayList<Comando> l = new ArrayList<>(); l.add(new Comando("abajo")); RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= IZQUIERDA 
            {
              Object RESULT =null;
		
        ArrayList<Comando> l = new ArrayList<>(); l.add(new Comando("izquierda")); RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= DERECHA 
            {
              Object RESULT =null;
		
        ArrayList<Comando> l = new ArrayList<>(); l.add(new Comando("derecha")); RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= INICIO NUMERO NUMERO 
            {
              Object RESULT =null;
		int xleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer x = (Integer)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((Symbol)CUP$parser$stack.peek()).left;
		int yright = ((Symbol)CUP$parser$stack.peek()).right;
		Integer y = (Integer)((Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<Comando> l = new ArrayList<>();
        l.add(new Comando("inicioX", x));
        l.add(new Comando("inicioY", y));
        RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_instrucciones ::= instruccion 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.peek()).left;
		int iright = ((Symbol)CUP$parser$stack.peek()).right;
		Object i = (Object)((Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = i;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_instrucciones ::= lista_instrucciones instruccion 
            {
              Object RESULT =null;
		int lileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int liright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object li = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int ileft = ((Symbol)CUP$parser$stack.peek()).left;
		int iright = ((Symbol)CUP$parser$stack.peek()).right;
		Object i = (Object)((Symbol) CUP$parser$stack.peek()).value;
		
        // Hacemos el cast antes de usar addAll
        ((ArrayList<Comando>) li).addAll((ArrayList<Comando>) i);
        RESULT = li;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_instrucciones 
            {
              Object RESULT =null;
		int lileft = ((Symbol)CUP$parser$stack.peek()).left;
		int liright = ((Symbol)CUP$parser$stack.peek()).right;
		Object li = (Object)((Symbol) CUP$parser$stack.peek()).value;
		
        // Le indicamos explícitamente a Java que 'li' es un ArrayList
        parser.listaComandos = (ArrayList<Comando>) li;
        RESULT = li;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

