
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 13 18:50:43 CST 2026
//----------------------------------------------------

package fes.aragon.tablerointerprete.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABAJO = 5;
  public static final int ARRIBA = 6;
  public static final int INICIO = 2;
  public static final int EOF = 0;
  public static final int IZQUIERDA = 4;
  public static final int NUMERO = 10;
  public static final int error = 1;
  public static final int DERECHA = 3;
  public static final int PARAR = 9;
  public static final int MOVER = 7;
  public static final int REPITE = 8;
}

